#!/usr/bin/env python3
#
# github-sync
#
# Copyright (C) 2017 Chris Lamb <chris@chris-lamb.co.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import logging
import eventlet
import requests
import subprocess

from xdg import BaseDirectory
from eventlet import wsgi
from configparser import SafeConfigParser

eventlet.monkey_patch()


class GithubSync(object):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.pool = eventlet.GreenPool(1000)

        self.load_config()
        self.setup_logging()

    def load_config(self):
        self.config = SafeConfigParser()
        self.config.read(
            os.path.join(BaseDirectory.xdg_config_home, 'github-sync.ini')
        )

        assert 'MAIN' in self.config

    def setup_logging(self):
        self.log = logging.getLogger()
        self.log.setLevel({
            0: logging.WARNING,
            1: logging.INFO,
            2: logging.DEBUG,
        }[1])

        handler = logging.StreamHandler(sys.stderr)
        handler.setFormatter(
            logging.Formatter('%(asctime).19s %(levelname).1s %(message)s')
        )
        self.log.addHandler(handler)

    def main(self):
        self.start_server()

        try:
            self.pool.waitall()
        except (SystemExit, KeyboardInterrupt):
            pass

        return 0

    def start_server(self):
        wsgi_socket = eventlet.listen((
            self.config['MAIN']['ListenAddress'],
            self.config['MAIN'].getint('ListenPort'),
        ))

        self.pool.spawn_n(wsgi.server, wsgi_socket, self.handle_wsgi)

    def handle_wsgi(self, env, start_response):
        if env['REQUEST_METHOD'] != 'POST':
            start_response("405 Method Not Allowed", [])
            return []

        if env['PATH_INFO'] == '/':
            for x in self.config.sections():
                if x == 'MAIN':
                    continue
                self.pool.spawn_n(self.sync_project, x)
        else:
            x = env['PATH_INFO'][1:]
            if x not in self.config:
                start_response("404 File Not Found", [])
                return []
            self.pool.spawn_n(self.sync_project, x)

        start_response("202 Accepted", [])
        return []

    def sync_project(self, name):
        self.log.info("Syncing %s", name)

        org = self.config['MAIN']['Organisation']
        project = self.config[name]

        data = {
            'name': name,
            'homepage': project['homepage'],
            'description': "Official mirror of {}".format(project['source']),
            'has_issues': False,
            'has_wiki': False,
            'has_downloads': False,
        }

        r = requests.patch(
            'https://api.github.com/repos/{}/{}'.format(org, name),
            json=data,
            headers=self.get_headers(),
        )

        if r.status_code != 200:
            r = requests.post(
                'https://api.github.com/orgs/{}/repos'.format(org),
                json=data,
                headers=self.get_headers(),
            )

            r.raise_for_status()

        cwd = os.path.join(BaseDirectory.xdg_cache_home, 'github-sync', name)
        repo = r.json()

        def git(*args, **kwargs):
            kwargs['args'] = ('git',) + args
            kwargs['cwd'] = kwargs.pop('cwd', cwd)

            self.log.debug("git %s", ' '.join(args))
            return subprocess.check_call(**kwargs)

        if os.path.exists(cwd):
            git('fetch')
        else:
            git('clone', project['source'], cwd, cwd=None)

        git('remote', 'set-url', 'origin', repo['ssh_url'])
        git('push', '--all')
        git('push', '--tags')

    def get_headers(self):
        return {
            'Accept': 'application/vnd.github.inertia-preview+json',
            'Authorization': 'token %s' % self.config['MAIN']['Token']
        }

if __name__ == '__main__':
    sys.exit(GithubSync().main())
